#!/usr/bin/env python3
"""Teya favicon set: generate, wire into the WordPress theme, check.

Generate (from the logo, or from initials + brand colour):
  python3 teya/scripts/teya_favicon.py --theme <theme_dir> --initials "ЭС" --color "#C8102E" --name "Эксперт Сервис" --wire
  python3 teya/scripts/teya_favicon.py --theme <theme_dir> --logo assets/images/logo-mark.svg --color "#C8102E" --name "..." --wire

Writes to <theme>/assets/favicon/:
  favicon.ico (16/32/48), favicon.svg, favicon-32x32.png, apple-touch-icon.png (180),
  android-chrome-192x192.png, android-chrome-512x512.png, site.webmanifest
and <theme>/inc/favicon.php (wp_head links, skipped when a WP Site Icon is set).
--wire adds `require_once get_template_directory() . '/inc/favicon.php';` to functions.php.

Check (used by teya_release_gate.py; no favicon = FAIL):
  python3 teya/scripts/teya_favicon.py --theme <theme_dir> --check [--url https://site/]
Exit: 0 ok, 1 fail, 2 cannot run.
"""
from __future__ import annotations

import argparse
import io
import json
import re
import shutil
import ssl
import sys
import urllib.request
from html.parser import HTMLParser
from pathlib import Path
from typing import Any
from urllib.parse import urljoin

FILES = ["favicon.ico", "favicon.svg", "favicon-32x32.png", "apple-touch-icon.png",
         "android-chrome-192x192.png", "android-chrome-512x512.png", "site.webmanifest"]
PNG_SIZES = {"favicon-32x32.png": 32, "apple-touch-icon.png": 180,
             "android-chrome-192x192.png": 192, "android-chrome-512x512.png": 512}
FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
    "/Library/Fonts/Arial Bold.ttf",
    "C:/Windows/Fonts/arialbd.ttf",
]
REQUIRE_LINE = "require_once get_template_directory() . '/inc/favicon.php';"

FAVICON_PHP = r"""<?php
/**
 * Favicon set generated by teya/scripts/teya_favicon.py.
 * If a Site Icon is set in Settings → General (site_icon), WordPress prints its own tags and we stay silent.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
function teya_favicon_tags() {
	if ( function_exists( 'has_site_icon' ) && has_site_icon() ) {
		return;
	}
	$base = get_template_directory_uri() . '/assets/favicon/';
	echo '<link rel="icon" href="' . esc_url( $base . 'favicon.ico' ) . '" sizes="any">' . "\n";
	echo '<link rel="icon" type="image/svg+xml" href="' . esc_url( $base . 'favicon.svg' ) . '">' . "\n";
	echo '<link rel="icon" type="image/png" sizes="32x32" href="' . esc_url( $base . 'favicon-32x32.png' ) . '">' . "\n";
	echo '<link rel="apple-touch-icon" sizes="180x180" href="' . esc_url( $base . 'apple-touch-icon.png' ) . '">' . "\n";
	echo '<link rel="manifest" href="' . esc_url( $base . 'site.webmanifest' ) . '">' . "\n";
	echo '<meta name="theme-color" content="__THEME_COLOR__">' . "\n";
}
add_action( 'wp_head', 'teya_favicon_tags', 2 );
"""


def hex_color(value: str) -> tuple[int, int, int]:
    v = value.strip().lstrip("#")
    if len(v) == 3:
        v = "".join(c * 2 for c in v)
    if not re.fullmatch(r"[0-9a-fA-F]{6}", v):
        raise SystemExit(f"bad colour: {value} (use #RRGGBB)")
    return tuple(int(v[i:i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def contrast_fg(bg: tuple[int, int, int]) -> str:
    lum = (0.299 * bg[0] + 0.587 * bg[1] + 0.114 * bg[2]) / 255
    return "#111111" if lum > 0.6 else "#FFFFFF"


def find_font(explicit: str | None) -> str | None:
    for cand in ([explicit] if explicit else []) + FONT_CANDIDATES:
        if cand and Path(cand).is_file():
            return cand
    return None


def initials_master(initials: str, bg: str, fg: str, font_path: str | None, radius: float) -> Any:
    from PIL import Image, ImageDraw, ImageFont

    size = 1024
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.rounded_rectangle([0, 0, size - 1, size - 1], radius=int(size * radius), fill=hex_color(bg) + (255,))
    text = initials.strip()[:3]
    if font_path:
        fsize = 620 if len(text) == 1 else (520 if len(text) == 2 else 400)
        font = ImageFont.truetype(font_path, fsize)
        while True:
            l, t, r, b = draw.textbbox((0, 0), text, font=font)
            if r - l <= size * 0.78 and b - t <= size * 0.62 or fsize < 80:
                break
            fsize -= 20
            font = ImageFont.truetype(font_path, fsize)
    else:
        font = ImageFont.load_default()
    l, t, r, b = draw.textbbox((0, 0), text, font=font)
    draw.text(((size - (r - l)) / 2 - l, (size - (b - t)) / 2 - t), text, font=font, fill=hex_color(fg) + (255,))
    return img


def initials_svg(initials: str, bg: str, fg: str, radius: float) -> str:
    text = initials.strip()[:3]
    fs = 36 if len(text) == 1 else (30 if len(text) == 2 else 22)
    rx = round(64 * radius, 1)
    esc = text.replace("&", "&amp;").replace("<", "&lt;")
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
            f'<rect width="64" height="64" rx="{rx}" fill="{bg}"/>'
            f'<text x="32" y="32" dy=".35em" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" '
            f'font-weight="700" font-size="{fs}" fill="{fg}">{esc}</text></svg>\n')


def render_svg(svg_path: Path, size: int = 1024) -> Any:
    from PIL import Image

    try:
        import cairosvg  # type: ignore

        return Image.open(io.BytesIO(cairosvg.svg2png(url=str(svg_path), output_width=size, output_height=size))).convert("RGBA")
    except ImportError:
        pass
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        raise SystemExit("SVG logo needs cairosvg or playwright to rasterize; or pass --initials instead")
    import base64

    data = base64.b64encode(svg_path.read_bytes()).decode()
    html = (f"<html><body style='margin:0;background:transparent'><img src='data:image/svg+xml;base64,{data}' "
            f"style='width:{size}px;height:{size}px;object-fit:contain;display:block'></body></html>")
    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        page = browser.new_page(viewport={"width": size, "height": size})
        page.set_content(html)
        png = page.screenshot(omit_background=True)
        browser.close()
    return Image.open(io.BytesIO(png)).convert("RGBA")


def logo_master(logo: Path, bg: str | None, radius: float, pad: float = 0.12) -> Any:
    from PIL import Image, ImageDraw

    src = render_svg(logo) if logo.suffix.lower() == ".svg" else Image.open(logo).convert("RGBA")
    bbox = src.getchannel("A").getbbox()
    if bbox:
        src = src.crop(bbox)
    size = 1024
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    if bg:
        ImageDraw.Draw(canvas).rounded_rectangle([0, 0, size - 1, size - 1], radius=int(size * radius), fill=hex_color(bg) + (255,))
    inner = int(size * (1 - 2 * pad))
    src.thumbnail((inner, inner), Image.LANCZOS)
    canvas.alpha_composite(src, ((size - src.width) // 2, (size - src.height) // 2))
    return canvas


def generate(args) -> int:
    try:
        from PIL import Image
    except ImportError:
        print("Pillow is required: pip install pillow", file=sys.stderr)
        return 2
    theme = Path(args.theme).resolve()
    out = theme / "assets" / "favicon"
    out.mkdir(parents=True, exist_ok=True)
    bg = args.color
    fg = args.fg or contrast_fg(hex_color(bg))
    radius = {"square": 0.0, "rounded": 0.18, "circle": 0.5}[args.shape]

    if args.logo:
        logo = Path(args.logo)
        if not logo.is_absolute() and not logo.is_file():
            logo = theme / args.logo
        if not logo.is_file():
            print(f"logo not found: {args.logo}", file=sys.stderr)
            return 2
        master = logo_master(logo, bg if not args.transparent else None, radius)
        if logo.suffix.lower() == ".svg":
            shutil.copyfile(logo, out / "favicon.svg")
        else:
            # Raster logo: embed the 64px PNG into an SVG wrapper so favicon.svg still exists and scales.
            import base64

            buf = io.BytesIO()
            master.resize((128, 128), Image.LANCZOS).save(buf, format="PNG")
            (out / "favicon.svg").write_text(
                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><image width="128" height="128" '
                f'href="data:image/png;base64,{base64.b64encode(buf.getvalue()).decode()}"/></svg>\n', encoding="utf-8")
    else:
        if not args.initials:
            print("give --logo or --initials", file=sys.stderr)
            return 2
        font = find_font(args.font)
        if not font:
            print("warning: no TTF font with Cyrillic found, using PIL default (pass --font)", file=sys.stderr)
        master = initials_master(args.initials, bg, fg, font, radius)
        (out / "favicon.svg").write_text(initials_svg(args.initials, bg, fg, radius), encoding="utf-8")

    for name, px in PNG_SIZES.items():
        im = master.resize((px, px), Image.LANCZOS)
        if name == "apple-touch-icon.png":  # iOS draws transparency as black — flatten on the brand colour
            flat = Image.new("RGBA", (px, px), hex_color(bg) + (255,))
            flat.alpha_composite(im)
            im = flat.convert("RGB")
        im.save(out / name, format="PNG", optimize=True)
    master.resize((256, 256), Image.LANCZOS).save(out / "favicon.ico", format="ICO", sizes=[(16, 16), (32, 32), (48, 48)])

    manifest = {
        "name": args.name or args.initials or "Site",
        "short_name": (args.short_name or args.name or args.initials or "Site")[:12],
        "icons": [
            {"src": "android-chrome-192x192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "android-chrome-512x512.png", "sizes": "512x512", "type": "image/png"},
        ],
        "theme_color": bg,
        "background_color": args.background or "#FFFFFF",
        "display": "standalone",
    }
    (out / "site.webmanifest").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    inc = theme / "inc"
    inc.mkdir(exist_ok=True)
    (inc / "favicon.php").write_text(FAVICON_PHP.replace("__THEME_COLOR__", bg), encoding="utf-8")
    wired = False
    if args.wire:
        fn = theme / "functions.php"
        text = fn.read_text(encoding="utf-8") if fn.is_file() else "<?php\n"
        if "inc/favicon.php" not in text:
            fn.write_text(text.rstrip() + "\n\n" + REQUIRE_LINE + "\n", encoding="utf-8")
        wired = True
    print(f"FAVICON GENERATED → {out} ({', '.join(FILES)}); inc/favicon.php written; wired={wired}")
    errors = check(theme, None)
    for e in errors:
        print(f"- {e}")
    return 0 if not errors else 1


class _LinkParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links: list[dict[str, str]] = []

    def handle_starttag(self, tag, attrs):
        if tag == "link":
            self.links.append({k: (v or "") for k, v in attrs})


def _get(url: str, timeout: int = 20) -> tuple[int, bytes, str]:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 TeyaFaviconCheck"})
    ctx = ssl.create_default_context()
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as r:
            return r.status, r.read(), r.geturl()
    except urllib.error.HTTPError as exc:
        return exc.code, b"", url
    except Exception as exc:  # noqa: BLE001
        return 0, str(exc).encode(), url


def check(theme: Path | None, url: str | None) -> list[str]:
    """Return a list of errors; empty list = favicon OK."""
    errors: list[str] = []
    if theme:
        fav = theme / "assets" / "favicon"
        missing = [f for f in FILES if not (fav / f).is_file() or (fav / f).stat().st_size == 0]
        site_icon_hint = any("site_icon" in p.read_text(encoding="utf-8", errors="ignore")
                             for p in list(theme.glob("*.php")) + list(theme.glob("inc/*.php")))
        if missing and not site_icon_hint:
            errors.append(f"favicon: нет файлов в {fav}: {', '.join(missing)} (запусти teya_favicon.py)")
        fn = theme / "functions.php"
        wired = fn.is_file() and ("inc/favicon.php" in fn.read_text(encoding="utf-8", errors="ignore")
                                  or "favicon" in fn.read_text(encoding="utf-8", errors="ignore"))
        if not wired and not site_icon_hint:
            errors.append("favicon: тема не подключает фавикон (нет require inc/favicon.php в functions.php и нет site_icon)")
        try:
            from PIL import Image

            for name, px in PNG_SIZES.items():
                p = fav / name
                if p.is_file():
                    with Image.open(p) as im:
                        if im.size != (px, px):
                            errors.append(f"favicon: {name} {im.size[0]}×{im.size[1]}, нужно {px}×{px}")
        except ImportError:
            pass
    if url:
        status, body, final = _get(url)
        if status != 200:
            errors.append(f"favicon: страница {url} вернула {status}")
            return errors
        parser = _LinkParser()
        parser.feed(body.decode("utf-8", errors="replace"))
        icons = [l for l in parser.links if "icon" in l.get("rel", "").lower().split() and l.get("href")]
        if not icons:
            errors.append(f"favicon: в <head> {url} нет <link rel=\"icon\">")
        for link in icons[:4]:
            href = urljoin(final, link["href"])
            if "w-logo-blue" in href or "wp-includes/images" in href:
                errors.append(f"favicon: подключён стандартный значок WordPress ({href})")
                continue
            st, data, _ = _get(href)
            if st != 200 or len(data) < 50:
                errors.append(f"favicon: {href} → HTTP {st}, {len(data)} байт")
        if not any("apple-touch-icon" in l.get("rel", "") for l in parser.links):
            errors.append("favicon: нет <link rel=\"apple-touch-icon\">")
        st, _data, final_ico = _get(urljoin(url, "/favicon.ico"))
        if "w-logo-blue" in final_ico:
            errors.append("favicon: /favicon.ico отдаёт логотип WordPress — задай site_icon или положи favicon.ico в корень сайта")
    return errors


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate / wire / check the favicon set for a WordPress theme.")
    ap.add_argument("--theme", help="Theme directory")
    ap.add_argument("--logo", help="Logo mark (SVG or PNG/WebP), path absolute or relative to the theme")
    ap.add_argument("--initials", help="1–3 letters when there is no logo mark, e.g. «ЭС»")
    ap.add_argument("--color", default="#1F2937", help="Brand colour #RRGGBB (icon background, theme-color)")
    ap.add_argument("--fg", help="Text colour for initials (default: auto contrast)")
    ap.add_argument("--background", help="Manifest background_color (default #FFFFFF)")
    ap.add_argument("--shape", choices=["square", "rounded", "circle"], default="rounded")
    ap.add_argument("--transparent", action="store_true", help="Logo mode: keep transparent background (except apple-touch-icon)")
    ap.add_argument("--name")
    ap.add_argument("--short-name")
    ap.add_argument("--font")
    ap.add_argument("--wire", action="store_true", help="Add require of inc/favicon.php to functions.php")
    ap.add_argument("--check", action="store_true", help="Only check (files + wiring [+ live HTML with --url])")
    ap.add_argument("--url", help="Rendered site URL to check <link rel=icon> (http/https)")
    args = ap.parse_args()
    if args.check:
        if not args.theme and not args.url:
            ap.error("--check needs --theme and/or --url")
        errors = check(Path(args.theme).resolve() if args.theme else None, args.url)
        print("FAVICON " + ("PASS" if not errors else "FAIL"))
        for e in errors:
            print(f"- {e}")
        return 0 if not errors else 1
    if not args.theme:
        ap.error("--theme is required to generate")
    return generate(args)


if __name__ == "__main__":
    raise SystemExit(main())
